IF
	OnCreation()
	Global("VP_ArunDead_Talks","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("VP_ArunDead_Talks","GLOBAL",1)
		CreateCreature("ArundelD",[282.309],4) // Arundel - Old Man
		CreateCreature("ArundelH",[282.309],4) // Arundel
END

IF
	!Global("RETURN_TO_LONELYWOOD","GLOBAL",0)
THEN
	RESPONSE #100
		StartCutSceneMode()
		StartCutScene("keRtrnLW")
		SetGlobal("RETURN_TO_LONELYWOOD","GLOBAL",0)
END


