IF
	NumTimesTalkedTo(0)
	See([PC])
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
		StartDialogueNoSet([PC])
END

IF
	Allegiance(Myself,NEUTRAL)
	OR(2)
		Global("VP_HalruaaHostile","GLOBAL",1)
		Global("VP_HalruaaAlarm","MYAREA",1)
THEN
	RESPONSE #100
		Enemy()
END

IF
	Allegiance(Myself,NEUTRAL)
	AttackedBy([PC],DEFAULT)
THEN
	RESPONSE #100
		SetGlobal("VP_HalruaaAlarm","MYAREA",1)
		Shout(99)
		Enemy()
END


