@echo off
cd override
tisunpack TT0001.tiz
tisunpack TT0002.tiz
tisunpack TT0003.tiz
tisunpack TT0007.tiz
tisunpack TT1001.tiz
tisunpack TT1002.tiz
tisunpack TT1003.tiz
tisunpack TT1005.tiz
tisunpack TT1006.tiz
tisunpack TT1007.tiz
tisunpack TT1008.tiz
tisunpack TT1009.tiz
tisunpack TT1010.tiz
tisunpack TT1011.tiz
tisunpack TT1012.tiz
tisunpack TT1014.tiz
tisunpack TT1015.tiz
tisunpack TT1016.tiz
tisunpack TT1200.tiz
tisunpack TT1201.tiz
tisunpack TT2000.tiz
tisunpack TT2001.tiz
tisunpack TT2002.tiz
tisunpack TT2003.tiz
tisunpack TT2004.tiz
tisunpack TT2005.tiz
tisunpack TT2006.tiz
tisunpack TT2100.tiz
tisunpack TT2101.tiz
tisunpack TT2102.tiz
tisunpack TT2103.tiz
tisunpack TT2104.tiz
tisunpack TT2105.tiz
tisunpack TT2106.tiz
tisunpack TT2107.tiz
tisunpack TT2108.tiz
tisunpack TT2109.tiz
tisunpack TT2110.tiz
tisunpack TT2111.tiz
tisunpack TT2112.tiz
tisunpack TT2113.tiz
tisunpack TT2114.tiz
tisunpack TT2115.tiz
tisunpack TT2116.tiz
tisunpack TT3001.tiz
tisunpack TT3101.tiz
tisunpack TT3201.tiz
tisunpack TT3301.tiz
tisunpack TT3401.tiz
tisunpack TT3501.tiz
tisunpack TT3502.tiz
tisunpack TT3503.tiz
tisunpack TT3600.tiz
tisunpack TT3601.tiz
tisunpack TT3602.tiz
tisunpack TT3603.tiz
tisunpack TT4000.tiz
tisunpack TT4001.tiz
tisunpack TT4002.tiz
tisunpack TT4003.tiz
tisunpack TT4004.tiz
tisunpack TT4005.tiz
tisunpack TT0070.tiz
tisunpack TT0068.tiz
tisunpack TT0066.tiz
tisunpack TT0065.tiz
tisunpack TT0064.tiz
tisunpack TT0063.tiz
tisunpack TT0060.tiz
tisunpack TT0057.tiz
tisunpack TT0058.tiz
tisunpack TT0059.tiz
tisunpack TT0071.tiz
tisunpack TT0072.tiz
tisunpack TT0073.tiz
tisunpack TT0074.tiz
tisunpack TT0077.tiz
tisunpack TT0078.tiz
tisunpack TT0079.tiz
tisunpack TT5000.tiz
tisunpack TT5001.tiz
tisunpack TT5002.tiz
tisunpack TT5003.tiz
tisunpack TT5004.tiz
tisunpack TT5101.tiz
tisunpack TT5102.tiz
tisunpack TT5103.tiz
tisunpack TT5104.tiz
tisunpack TT5201.tiz
tisunpack TT5202.tiz
tisunpack TT5203.tiz
tisunpack TT5204.tiz
tisunpack TT5301.tiz
tisunpack TT5302.tiz
tisunpack TT5303.tiz
tisunpack TT5304.tiz
tisunpack TT5401.tiz
tisunpack TT5402.tiz
tisunpack TT5403.tiz
tisunpack TT5404.tiz
tisunpack TT5502.tiz
tisunpack TT6001.tiz
tisunpack TT6002.tiz
tisunpack TT6003.tiz
tisunpack TT6004.tiz
tisunpack TT6005.tiz
tisunpack TT6006.tiz
tisunpack TT6007.tiz
tisunpack TT6008.tiz
tisunpack TT6009.tiz
tisunpack TT6010.tiz
tisunpack TT6011.tiz
tisunpack TT6013.tiz
tisunpack TT6014.tiz
tisunpack TT7000.tiz
tisunpack TT7001.tiz
tisunpack TT7002.tiz
tisunpack TT7003.tiz
tisunpack TT7004.tiz
tisunpack TT7005.tiz
tisunpack AR0015.tiz
tisunpack AR6600.tiz
tisunpack AR7100.tiz
tisunpack AR8700.tiz
del TT0001.tiz
del TT0002.tiz
del TT0003.tiz
del TT0007.tiz
del TT1001.tiz
del TT1002.tiz
del TT1003.tiz
del TT1005.tiz
del TT1006.tiz
del TT1007.tiz
del TT1008.tiz
del TT1009.tiz
del TT1010.tiz
del TT1011.tiz
del TT1012.tiz
del TT1014.tiz
del TT1015.tiz
del TT1016.tiz
del TT1200.tiz
del TT1201.tiz
del TT2000.tiz
del TT2001.tiz
del TT2002.tiz
del TT2003.tiz
del TT2004.tiz
del TT2005.tiz
del TT2006.tiz
del TT2100.tiz
del TT2101.tiz
del TT2102.tiz
del TT2103.tiz
del TT2104.tiz
del TT2105.tiz
del TT2106.tiz
del TT2107.tiz
del TT2108.tiz
del TT2109.tiz
del TT2110.tiz
del TT2111.tiz
del TT2112.tiz
del TT2113.tiz
del TT2114.tiz
del TT2115.tiz
del TT2116.tiz
del TT3001.tiz
del TT3101.tiz
del TT3201.tiz
del TT3301.tiz
del TT3401.tiz
del TT3501.tiz
del TT3502.tiz
del TT3503.tiz
del TT3600.tiz
del TT3601.tiz
del TT3602.tiz
del TT3603.tiz
del TT4000.tiz
del TT4001.tiz
del TT4002.tiz
del TT4003.tiz
del TT4004.tiz
del TT4005.tiz
del TT0070.tiz
del TT0068.tiz
del TT0066.tiz
del TT0065.tiz
del TT0064.tiz
del TT0063.tiz
del TT0060.tiz
del TT0057.tiz
del TT0058.tiz
del TT0059.tiz
del TT0071.tiz
del TT0072.tiz
del TT0073.tiz
del TT0074.tiz
del TT0077.tiz
del TT0078.tiz
del TT0079.tiz
del TT5000.tiz
del TT5001.tiz
del TT5002.tiz
del TT5003.tiz
del TT5004.tiz
del TT5101.tiz
del TT5102.tiz
del TT5103.tiz
del TT5104.tiz
del TT5201.tiz
del TT5202.tiz
del TT5203.tiz
del TT5204.tiz
del TT5301.tiz
del TT5302.tiz
del TT5303.tiz
del TT5304.tiz
del TT5401.tiz
del TT5402.tiz
del TT5403.tiz
del TT5404.tiz
del TT5502.tiz
del TT6001.tiz
del TT6002.tiz
del TT6003.tiz
del TT6004.tiz
del TT6005.tiz
del TT6006.tiz
del TT6007.tiz
del TT6008.tiz
del TT6009.tiz
del TT6010.tiz
del TT6011.tiz
del TT6013.tiz
del TT6014.tiz
del TT7000.tiz
del TT7001.tiz
del TT7002.tiz
del TT7003.tiz
del TT7004.tiz
del TT7005.tiz
del AR0015.tiz
del AR6600.tiz
del AR7100.tiz
del AR8700.tiz
del tisunpack.exe
oggdec ARUN_01.ogg                                       
oggdec ARUN_02.ogg                                       
oggdec ARUN_03.ogg                                       
oggdec ARUN_04.ogg                                       
oggdec ARUN_05.ogg                                       
oggdec ARUN_06.ogg                                       
oggdec ARUN_07.ogg                                       
oggdec ARUN_08.ogg                                       
oggdec ARUN_09.ogg                                       
oggdec ARUN_12.ogg                                       
oggdec ARUN_13.ogg                                       
oggdec ARUN_14.ogg                                       
oggdec ARUN_15.ogg                                       
oggdec ARUN_16.ogg                                       
oggdec ARUN_17.ogg                                       
oggdec ARUN_18.ogg                                       
oggdec ARUN_19.ogg                                       
oggdec ARUN_20.ogg                                       
oggdec ARUN_21.ogg                                       
oggdec ARUN_22.ogg                                       
oggdec ARUN_23.ogg                                       
oggdec ARUN_24.ogg                                       
oggdec ARUN_25.ogg                                       
oggdec ARUN_26.ogg                                       
oggdec ARUN_27.ogg                                       
oggdec ARUN_28.ogg                                       
oggdec ARUN_29.ogg                                       
oggdec ARUN_30.ogg                                       
oggdec ARUN_31.ogg                                       
oggdec ARUN_32.ogg                                       
oggdec ARUN_33.ogg                                       
oggdec ARUN_34.ogg                                       
oggdec ARUN_35.ogg                                       
oggdec ARUN_36.ogg                                       
oggdec ARUN_37.ogg                                       
oggdec ARUN_38.ogg                                       
oggdec ARUN_39.ogg                                       
oggdec ARUN_40.ogg                                       
oggdec ARUN_41.ogg                                       
oggdec ARUN_42.ogg                                       
oggdec ARUN_43.ogg                                       
oggdec ARUN_44.ogg                                       
oggdec ARUN_45.ogg                                       
oggdec ARUN_46.ogg                                       
oggdec ARUN_47.ogg                                       
oggdec ARUN_48.ogg                                       
oggdec ARUN_49.ogg                                       
oggdec ARUN_50.ogg                                       
oggdec ARUN_51.ogg                                       
oggdec ARUN_52.ogg                                       
oggdec ARUN_53.ogg                                       
oggdec ARUN_54.ogg                                       
oggdec ARUN_55.ogg                                       
oggdec ARUN_56.ogg                                       
oggdec ARUN_57.ogg                                       
oggdec ARUN_58.ogg                                       
oggdec ARUN_59.ogg                                       
oggdec ARUN_60.ogg                                       
oggdec ARUN_62.ogg                                       
oggdec ARUN_63.ogg                                       
oggdec ARUN_64.ogg                                       
oggdec ARUN_65.ogg                                       
oggdec ARUN_66.ogg                                       
oggdec ARUN_67.ogg                                       
oggdec ARUN_68.ogg                                       
oggdec ARUN_69.ogg                                       
oggdec ARUN_70.ogg                                       
oggdec ARUN_71.ogg                                       
oggdec ARUN_72.ogg                                       
oggdec ARUN_73.ogg                                       
oggdec ARUN_74.ogg                                       
oggdec ARUN_75.ogg                                       
oggdec ARUN_76.ogg                                       
oggdec ARUN_77.ogg                                       
oggdec ARUN_78.ogg                                       
oggdec ARUN_79.ogg                                       
oggdec ARUN_81.ogg                                       
oggdec ARUN_82.ogg                                       
oggdec ARUN_83.ogg                                       
oggdec ARUN_84.ogg                                       
oggdec ARUN_85.ogg                                       
oggdec ARUN_86.ogg                                       
oggdec ARUN_87.ogg                                       
oggdec Beetboom.ogg                                      
oggdec BRANW01.ogg                                       
oggdec BRANW02.ogg                                       
oggdec BRANW03.ogg                                       
oggdec BRANW04.ogg                                       
oggdec BRANW05.ogg                                       
oggdec BRANW06.ogg                                       
oggdec BRANW07.ogg                                       
oggdec BRANW08.ogg                                       
oggdec BRANW09.ogg                                       
oggdec BRANW10.ogg                                       
oggdec BRANW11.ogg                                       
oggdec BRANW17.ogg                                       
oggdec BRANW18.ogg                                       
oggdec BRANW19.ogg                                       
oggdec BRANW20.ogg                                       
oggdec BRANW21.ogg                                       
oggdec BRANW22.ogg                                       
oggdec BRANW23.ogg                                       
oggdec BRANW24.ogg                                       
oggdec BRANW25.ogg                                       
oggdec BRANW26.ogg                                       
oggdec BRANW27.ogg                                       
oggdec BRANW28.ogg                                       
oggdec BRANW29.ogg                                       
oggdec BRANW30.ogg                                       
oggdec BRANW31.ogg                                       
oggdec BRANW32.ogg                                       
oggdec BRANW33.ogg                                       
oggdec BRANW34.ogg                                       
oggdec BRANW35.ogg                                       
oggdec BRANW36.ogg                                       
oggdec BRANW37.ogg                                       
oggdec BRANW38.ogg                                       
oggdec BRANW39.ogg                                       
oggdec BRANW40.ogg                                       
oggdec BRANW41.ogg
oggdec DAR_C01.ogg
oggdec DAR_C02.ogg
oggdec DAR_C03.ogg
oggdec DAR_C04.ogg
oggdec DAR_C05.ogg
oggdec DAR_C06.ogg
oggdec DAR_C07.ogg
oggdec DAR_C08.ogg
oggdec DAR_C09.ogg
oggdec DAR_C10.ogg
oggdec DAR_C11.ogg
oggdec DAR_C12.ogg
oggdec DAR_C13.ogg
oggdec DAR_C14.ogg
oggdec DAR_C15.ogg
oggdec DAR_C16.ogg
oggdec DAR_C17.ogg
oggdec DAR_C18.ogg
oggdec DAR_C19.ogg
oggdec DAR_C20.ogg
oggdec DAR_C21.ogg
oggdec DAR_C22.ogg
oggdec DAR_C23.ogg
oggdec DAR_C24.ogg
oggdec DAR_C25.ogg
oggdec DAR_C26.ogg
oggdec DAR_C27.ogg
oggdec DAR_C28.ogg
oggdec DAR_C29.ogg
oggdec DAR_C30.ogg
oggdec DAR_C31.ogg
oggdec DAR_C32.ogg
oggdec DAR_C33.ogg
oggdec DAR_C34.ogg
oggdec HMONE001.ogg
oggdec HMONE003.ogg
oggdec HMONE004.ogg
oggdec HMONE005.ogg
oggdec HMONE006.ogg
oggdec HMONE007.ogg
oggdec HMONE008.ogg
oggdec HMONE009.ogg
oggdec HMONE010.ogg
oggdec HMONE011.ogg
oggdec HMONE012.ogg
oggdec HMONE013.ogg
oggdec HMONE014.ogg
oggdec HMONE015.ogg
oggdec HMONE017.ogg
oggdec HMONE018.ogg
oggdec HMONE019.ogg
oggdec HMONE020.ogg
oggdec HMONE021.ogg
oggdec HMONE022.ogg
oggdec HMONE023.ogg
oggdec HMONE024.ogg
oggdec HMONE025.ogg
oggdec HMONE026.ogg
oggdec HMONE027.ogg
oggdec HMONE028.ogg
oggdec HMONE029.ogg
oggdec HMONE030.ogg
oggdec HMONE031.ogg
oggdec HMONE032.ogg
oggdec HMONE034.ogg
oggdec HMONE035.ogg
oggdec HMONE038.ogg
oggdec HMONE040.ogg
oggdec HROT_01.ogg
oggdec HROT_02.ogg
oggdec HROT_03.ogg
oggdec HROT_04.ogg
oggdec HROT_05.ogg
oggdec HROT_06.ogg
oggdec HROT_07.ogg
oggdec HROT_08.ogg
oggdec HROT_09.ogg
oggdec HROT_10.ogg
oggdec HROT_11.ogg
oggdec HROT_12.ogg
oggdec HROT_13.ogg
oggdec HROT_14.ogg
oggdec HROT_15.ogg
oggdec HROT_16.ogg
oggdec HROT_17.ogg
oggdec HROT_18.ogg
oggdec HROT_19.ogg
oggdec HROT_20.ogg
oggdec HROT_21.ogg
oggdec HROT_22.ogg
oggdec HROT_23.ogg
oggdec HROT_24.ogg
oggdec HROT_25.ogg
oggdec HROT_26.ogg
oggdec HROT_27.ogg
oggdec HROT_28.ogg
oggdec HROT_29.ogg
oggdec HROT_30.ogg
oggdec HROT_31.ogg
oggdec HROT_32.ogg
oggdec HROT_33.ogg
oggdec HROT_34.ogg
oggdec HROT_35.ogg
oggdec HROT_36.ogg
oggdec HROT_37.ogg
oggdec HROT_38.ogg
oggdec HROT_39.ogg
oggdec HROT_40.ogg
oggdec KRES_01.ogg                                       
oggdec KRES_02.ogg                                       
oggdec KRES_03.ogg                                       
oggdec KRES_04.ogg                                       
oggdec KRES_05.ogg                                       
oggdec KRES_06.ogg                                       
oggdec KRES_07.ogg                                       
oggdec KRES_08.ogg                                       
oggdec KRES_09.ogg                                       
oggdec KRES_10.ogg                                       
oggdec KRES_11.ogg                                       
oggdec KRES_12.ogg                                       
oggdec KRES_13.ogg                                       
oggdec KRES_14.ogg                                       
oggdec KRES_15.ogg                                       
oggdec KRES_16.ogg                                       
oggdec KRES_17.ogg                                       
oggdec KRES_18.ogg                                       
oggdec KRES_19.ogg                                       
oggdec KRES_20.ogg                                       
oggdec KRES_21.ogg                                       
oggdec KRES_22.ogg                                       
oggdec KRES_23.ogg                                       
oggdec KRES_24.ogg                                       
oggdec KRES_25.ogg                                       
oggdec KRES_26.ogg                                       
oggdec KRES_27.ogg                                       
oggdec KRES_28.ogg                                       
oggdec KRES_29.ogg                                       
oggdec KRES_30.ogg                                       
oggdec KRES_31.ogg                                       
oggdec KRES_32.ogg                                       
oggdec KRES_33.ogg                                       
oggdec KRES_34.ogg                                       
oggdec KRES_35.ogg                                       
oggdec KRES_36.ogg                                       
oggdec KRES_39.ogg                                       
oggdec KRES_40.ogg                                       
oggdec KRES_41.ogg                                       
oggdec KRES_42.ogg                                                                            
oggdec VERBEE01.ogg                                      
oggdec VERBEE02.ogg                                      
oggdec VERBEE03.ogg                                      
oggdec VERBEE04.ogg                                      
oggdec VERBEE07.ogg                                      
oggdec VERBEE08.ogg                                      
oggdec VERBEE09.ogg                                      
oggdec VERBEE10.ogg                                      
oggdec VERBEE11.ogg                                      
oggdec YETI01.ogg                                        
oggdec YETI02.ogg                                        
oggdec YETI03.ogg                                        
oggdec YETI04.ogg                                        
oggdec YETI07.ogg                                        
oggdec YETI08.ogg                                        
oggdec YETI09.ogg                                        
oggdec YETI10.ogg                                        
oggdec YETI11.ogg                                        
oggdec YETI12.ogg                                        
oggdec YXUN_01.ogg                                       
oggdec YXUN_02.ogg                                       
oggdec YXUN_03.ogg                                       
oggdec YXUN_04.ogg                                       
oggdec YXUN_05.ogg                                       
oggdec YXUN_06.ogg                                       
oggdec YXUN_07.ogg                                       
oggdec YXUN_08.ogg                                       
oggdec YXUN_09.ogg                                       
oggdec YXUN_10.ogg                                       
oggdec YXUN_11.ogg                                       
oggdec YXUN_12.ogg                                       
oggdec YXUN_13.ogg                                       
oggdec YXUN_14.ogg                                       
oggdec YXUN_15.ogg                                       
oggdec YXUN_16.ogg                                       
oggdec YXUN_17.ogg                                       
oggdec YXUN_18.ogg                                       
oggdec YXUN_19.ogg                                       
oggdec YXUN_20.ogg                                       
oggdec YXUN_21.ogg                                       
oggdec YXUN_22.ogg                                       
oggdec YXUN_23.ogg                                       
oggdec YXUN_24.ogg                                       
oggdec YXUN_25.ogg                                       
oggdec YXUN_26.ogg                                       
oggdec YXUN_27.ogg                                       
oggdec YXUN_28.ogg                                       
oggdec YXUN_29.ogg                                       
oggdec YXUN_30.ogg                                       
oggdec YXUN_31.ogg                                       
oggdec YXUN_32.ogg                                       
oggdec YXUN_33.ogg                                       
oggdec YXUN_34.ogg                                       
oggdec YXUN_35.ogg                                       
oggdec YXUN_36.ogg                                       
oggdec YXUN_37.ogg                                       
oggdec YXUN_38.ogg                                       
oggdec YXUN_39.ogg                                       
oggdec YXUN_40.ogg                                       
oggdec YXUN_41.ogg                                       
oggdec YXUN_42.ogg
oggdec avalanch.ogg                                      
oggdec LARR_01.ogg                                       
oggdec LARR_02.ogg                                       
oggdec LARR_10.ogg                                       
oggdec LARR_12.ogg                                       
oggdec LARR_13.ogg                                       
oggdec LARR_14.ogg                                       
oggdec LARR_15.ogg                                       
oggdec LARR_16.ogg                                       
oggdec LARR_17.ogg                                       
oggdec LARR_18.ogg                                       
oggdec LARR_19.ogg                                       
oggdec LARR_20.ogg                                       
oggdec LARR_21.ogg                                       
oggdec LARR_22.ogg                                       
oggdec LARR_23.ogg                                       
oggdec LARR_24.ogg                                       
oggdec LARR_25.ogg                                       
oggdec LARR_26.ogg                                       
oggdec LARR_27.ogg                                       
oggdec LARR_28.ogg                                       
oggdec LARR_30.ogg                                       
oggdec LARR_32.ogg                                       
oggdec LARR_33.ogg                                       
oggdec LARR_34.ogg                                       
oggdec LARR_35.ogg                                       
oggdec LARR_36.ogg                                       
oggdec LARR_37.ogg                                       
oggdec LARR_38.ogg                                       
oggdec LARR_39.ogg                                       
oggdec LARR_40.ogg                                       
oggdec LARR_41.ogg                                       
oggdec LARR_42.ogg                                       
oggdec LARR_43.ogg                                       
oggdec LARR_44.ogg                                       
oggdec LARR_45.ogg                                       
oggdec LARR_46.ogg                                       
oggdec LARR_47.ogg                                       
oggdec LARR_48.ogg                                       
oggdec LARR_49.ogg                                       
oggdec LARR_50.ogg                                       
oggdec LARR_51.ogg                                       
oggdec LARR_52.ogg                                       
oggdec LARR_53.ogg                                       
oggdec LARR_54.ogg                                       
oggdec LARR_55.ogg                                       
oggdec LARR_56.ogg                                       
oggdec scry.ogg
oggdec stagnes.ogg
oggdec intro1.ogg
oggdec intro2.ogg
oggdec intro3.ogg
oggdec intro4.ogg
oggdec intro5.ogg
oggdec ThemeNEJ.ogg
oggdec tilorn01.ogg
oggdec tilorn02.ogg
oggdec tilorn03.ogg
oggdec tilorn04.ogg
oggdec tilorn05.ogg
oggdec tilorn06.ogg
oggdec tilorn07.ogg
oggdec tilorn08.ogg
oggdec tilorn09.ogg
oggdec tilorn10.ogg
oggdec tilorn11.ogg
oggdec tilorn12.ogg
oggdec tilorn13.ogg
oggdec tilorn14.ogg
oggdec tilorn15.ogg
oggdec tilorn16.ogg
oggdec tilorn17.ogg
oggdec tilorn18.ogg
oggdec tilorn19.ogg
oggdec tilorn20.ogg
oggdec tilorn21.ogg
oggdec tilorn22.ogg
oggdec tilorn23.ogg
oggdec tilorn24.ogg
oggdec tilorn25.ogg
oggdec tilorn26.ogg
oggdec tilorn27.ogg
oggdec tilorn28.ogg
oggdec tilorn29.ogg
oggdec tilorn30.ogg
oggdec tilorn31.ogg
oggdec tilorn32.ogg
oggdec tilorn33.ogg
oggdec CBooAct1.ogg
oggdec CBooAct2.ogg
oggdec CBooAct3.ogg
oggdec CBooAtt1.ogg
oggdec CBooAtt2.ogg
oggdec CBooAtt3.ogg
oggdec CBooCrHi.ogg
oggdec CBooCrMi.ogg
oggdec CBooHurt.ogg
oggdec CBooSel1.ogg
oggdec CBooSel2.ogg
oggdec CBooSel3.ogg
oggdec CBooSpFa.ogg
del ARUN_01.ogg                                       
del ARUN_02.ogg                                       
del ARUN_03.ogg                                       
del ARUN_04.ogg                                       
del ARUN_05.ogg                                       
del ARUN_06.ogg                                       
del ARUN_07.ogg                                       
del ARUN_08.ogg                                       
del ARUN_09.ogg                                       
del ARUN_12.ogg                                       
del ARUN_13.ogg                                       
del ARUN_14.ogg                                       
del ARUN_15.ogg                                       
del ARUN_16.ogg                                       
del ARUN_17.ogg                                       
del ARUN_18.ogg                                       
del ARUN_19.ogg                                       
del ARUN_20.ogg                                       
del ARUN_21.ogg                                       
del ARUN_22.ogg                                       
del ARUN_23.ogg                                       
del ARUN_24.ogg                                       
del ARUN_25.ogg                                       
del ARUN_26.ogg                                       
del ARUN_27.ogg                                       
del ARUN_28.ogg                                       
del ARUN_29.ogg                                       
del ARUN_30.ogg                                       
del ARUN_31.ogg                                       
del ARUN_32.ogg                                       
del ARUN_33.ogg                                       
del ARUN_34.ogg                                       
del ARUN_35.ogg                                       
del ARUN_36.ogg                                       
del ARUN_37.ogg                                       
del ARUN_38.ogg                                       
del ARUN_39.ogg                                       
del ARUN_40.ogg                                       
del ARUN_41.ogg                                       
del ARUN_42.ogg                                       
del ARUN_43.ogg                                       
del ARUN_44.ogg                                       
del ARUN_45.ogg                                       
del ARUN_46.ogg                                       
del ARUN_47.ogg                                       
del ARUN_48.ogg                                       
del ARUN_49.ogg                                       
del ARUN_50.ogg                                       
del ARUN_51.ogg                                       
del ARUN_52.ogg                                       
del ARUN_53.ogg                                       
del ARUN_54.ogg                                       
del ARUN_55.ogg                                       
del ARUN_56.ogg                                       
del ARUN_57.ogg                                       
del ARUN_58.ogg                                       
del ARUN_59.ogg                                       
del ARUN_60.ogg                                       
del ARUN_62.ogg                                       
del ARUN_63.ogg                                       
del ARUN_64.ogg                                       
del ARUN_65.ogg                                       
del ARUN_66.ogg                                       
del ARUN_67.ogg                                       
del ARUN_68.ogg                                       
del ARUN_69.ogg                                       
del ARUN_70.ogg                                       
del ARUN_71.ogg                                       
del ARUN_72.ogg                                       
del ARUN_73.ogg                                       
del ARUN_74.ogg                                       
del ARUN_75.ogg                                       
del ARUN_76.ogg                                       
del ARUN_77.ogg                                       
del ARUN_78.ogg                                       
del ARUN_79.ogg                                       
del ARUN_81.ogg                                       
del ARUN_82.ogg                                       
del ARUN_83.ogg                                       
del ARUN_84.ogg                                       
del ARUN_85.ogg                                       
del ARUN_86.ogg                                       
del ARUN_87.ogg                                       
del Beetboom.ogg                                      
del BRANW01.ogg                                       
del BRANW02.ogg                                       
del BRANW03.ogg                                       
del BRANW04.ogg                                       
del BRANW05.ogg                                       
del BRANW06.ogg                                       
del BRANW07.ogg                                       
del BRANW08.ogg                                       
del BRANW09.ogg                                       
del BRANW10.ogg                                       
del BRANW11.ogg                                       
del BRANW17.ogg                                       
del BRANW18.ogg                                       
del BRANW19.ogg                                       
del BRANW20.ogg                                       
del BRANW21.ogg                                       
del BRANW22.ogg                                       
del BRANW23.ogg                                       
del BRANW24.ogg                                       
del BRANW25.ogg                                       
del BRANW26.ogg                                       
del BRANW27.ogg                                       
del BRANW28.ogg                                       
del BRANW29.ogg                                       
del BRANW30.ogg                                       
del BRANW31.ogg                                       
del BRANW32.ogg                                       
del BRANW33.ogg                                       
del BRANW34.ogg                                       
del BRANW35.ogg                                       
del BRANW36.ogg                                       
del BRANW37.ogg                                       
del BRANW38.ogg                                       
del BRANW39.ogg                                       
del BRANW40.ogg                                       
del BRANW41.ogg
del DAR_C01.ogg
del DAR_C02.ogg
del DAR_C03.ogg
del DAR_C04.ogg
del DAR_C05.ogg
del DAR_C06.ogg
del DAR_C07.ogg
del DAR_C08.ogg
del DAR_C09.ogg
del DAR_C10.ogg
del DAR_C11.ogg
del DAR_C12.ogg
del DAR_C13.ogg
del DAR_C14.ogg
del DAR_C15.ogg
del DAR_C16.ogg
del DAR_C17.ogg
del DAR_C18.ogg
del DAR_C19.ogg
del DAR_C20.ogg
del DAR_C21.ogg
del DAR_C22.ogg
del DAR_C23.ogg
del DAR_C24.ogg
del DAR_C25.ogg
del DAR_C26.ogg
del DAR_C27.ogg
del DAR_C28.ogg
del DAR_C29.ogg
del DAR_C30.ogg
del DAR_C31.ogg
del DAR_C32.ogg
del DAR_C33.ogg
del DAR_C34.ogg
del HMONE001.ogg
del HMONE003.ogg
del HMONE004.ogg
del HMONE005.ogg
del HMONE006.ogg
del HMONE007.ogg
del HMONE008.ogg
del HMONE009.ogg
del HMONE010.ogg
del HMONE011.ogg
del HMONE012.ogg
del HMONE013.ogg
del HMONE014.ogg
del HMONE015.ogg
del HMONE017.ogg
del HMONE018.ogg
del HMONE019.ogg
del HMONE020.ogg
del HMONE021.ogg
del HMONE022.ogg
del HMONE023.ogg
del HMONE024.ogg
del HMONE025.ogg
del HMONE026.ogg
del HMONE027.ogg
del HMONE028.ogg
del HMONE029.ogg
del HMONE030.ogg
del HMONE031.ogg
del HMONE032.ogg
del HMONE034.ogg
del HMONE035.ogg
del HMONE038.ogg
del HMONE040.ogg
del HROT_01.ogg
del HROT_02.ogg
del HROT_03.ogg
del HROT_04.ogg
del HROT_05.ogg
del HROT_06.ogg
del HROT_07.ogg
del HROT_08.ogg
del HROT_09.ogg
del HROT_10.ogg
del HROT_11.ogg
del HROT_12.ogg
del HROT_13.ogg
del HROT_14.ogg
del HROT_15.ogg
del HROT_16.ogg
del HROT_17.ogg
del HROT_18.ogg
del HROT_19.ogg
del HROT_20.ogg
del HROT_21.ogg
del HROT_22.ogg
del HROT_23.ogg
del HROT_24.ogg
del HROT_25.ogg
del HROT_26.ogg
del HROT_27.ogg
del HROT_28.ogg
del HROT_29.ogg
del HROT_30.ogg
del HROT_31.ogg
del HROT_32.ogg
del HROT_33.ogg
del HROT_34.ogg
del HROT_35.ogg
del HROT_36.ogg
del HROT_37.ogg
del HROT_38.ogg
del HROT_39.ogg
del HROT_40.ogg
del KRES_01.ogg                                       
del KRES_02.ogg                                       
del KRES_03.ogg                                       
del KRES_04.ogg                                       
del KRES_05.ogg                                       
del KRES_06.ogg                                       
del KRES_07.ogg                                       
del KRES_08.ogg                                       
del KRES_09.ogg                                       
del KRES_10.ogg                                       
del KRES_11.ogg                                       
del KRES_12.ogg                                       
del KRES_13.ogg                                       
del KRES_14.ogg                                       
del KRES_15.ogg                                       
del KRES_16.ogg                                       
del KRES_17.ogg                                       
del KRES_18.ogg                                       
del KRES_19.ogg                                       
del KRES_20.ogg                                       
del KRES_21.ogg                                       
del KRES_22.ogg                                       
del KRES_23.ogg                                       
del KRES_24.ogg                                       
del KRES_25.ogg                                       
del KRES_26.ogg                                       
del KRES_27.ogg                                       
del KRES_28.ogg                                       
del KRES_29.ogg                                       
del KRES_30.ogg                                       
del KRES_31.ogg                                       
del KRES_32.ogg                                       
del KRES_33.ogg                                       
del KRES_34.ogg                                       
del KRES_35.ogg                                       
del KRES_36.ogg                                       
del KRES_39.ogg                                       
del KRES_40.ogg                                       
del KRES_41.ogg
del KRES_42.ogg
del VERBEE01.ogg                                      
del VERBEE02.ogg                                      
del VERBEE03.ogg                                      
del VERBEE04.ogg                                      
del VERBEE07.ogg                                      
del VERBEE08.ogg                                      
del VERBEE09.ogg                                      
del VERBEE10.ogg                                      
del VERBEE11.ogg                                      
del YETI01.ogg                                        
del YETI02.ogg                                        
del YETI03.ogg                                        
del YETI04.ogg                                        
del YETI07.ogg                                        
del YETI08.ogg                                        
del YETI09.ogg                                        
del YETI10.ogg                                        
del YETI11.ogg                                        
del YETI12.ogg                                        
del YXUN_01.ogg                                       
del YXUN_02.ogg                                       
del YXUN_03.ogg                                       
del YXUN_04.ogg                                       
del YXUN_05.ogg                                       
del YXUN_06.ogg                                       
del YXUN_07.ogg                                       
del YXUN_08.ogg                                       
del YXUN_09.ogg                                       
del YXUN_10.ogg                                       
del YXUN_11.ogg                                       
del YXUN_12.ogg                                       
del YXUN_13.ogg                                       
del YXUN_14.ogg                                       
del YXUN_15.ogg                                       
del YXUN_16.ogg                                       
del YXUN_17.ogg                                       
del YXUN_18.ogg                                       
del YXUN_19.ogg                                       
del YXUN_20.ogg                                       
del YXUN_21.ogg                                       
del YXUN_22.ogg                                       
del YXUN_23.ogg                                       
del YXUN_24.ogg                                       
del YXUN_25.ogg                                       
del YXUN_26.ogg                                       
del YXUN_27.ogg                                       
del YXUN_28.ogg                                       
del YXUN_29.ogg                                       
del YXUN_30.ogg                                       
del YXUN_31.ogg                                       
del YXUN_32.ogg                                       
del YXUN_33.ogg                                       
del YXUN_34.ogg                                       
del YXUN_35.ogg                                       
del YXUN_36.ogg                                       
del YXUN_37.ogg                                       
del YXUN_38.ogg                                       
del YXUN_39.ogg                                       
del YXUN_40.ogg                                       
del YXUN_41.ogg                                       
del YXUN_42.ogg                                    
del avalanch.ogg                                      
del LARR_01.ogg                                       
del LARR_02.ogg                                       
del LARR_10.ogg                                       
del LARR_12.ogg                                       
del LARR_13.ogg                                       
del LARR_14.ogg                                       
del LARR_15.ogg                                       
del LARR_16.ogg                                       
del LARR_17.ogg                                       
del LARR_18.ogg                                       
del LARR_19.ogg                                       
del LARR_20.ogg                                       
del LARR_21.ogg                                       
del LARR_22.ogg                                       
del LARR_23.ogg                                       
del LARR_24.ogg                                       
del LARR_25.ogg                                       
del LARR_26.ogg                                       
del LARR_27.ogg                                       
del LARR_28.ogg                                       
del LARR_30.ogg                                       
del LARR_32.ogg                                       
del LARR_33.ogg                                       
del LARR_34.ogg                                       
del LARR_35.ogg                                       
del LARR_36.ogg                                       
del LARR_37.ogg                                       
del LARR_38.ogg                                       
del LARR_39.ogg                                       
del LARR_40.ogg                                       
del LARR_41.ogg                                       
del LARR_42.ogg                                       
del LARR_43.ogg                                       
del LARR_44.ogg                                       
del LARR_45.ogg                                       
del LARR_46.ogg                                       
del LARR_47.ogg                                       
del LARR_48.ogg                                       
del LARR_49.ogg                                       
del LARR_50.ogg                                       
del LARR_51.ogg                                       
del LARR_52.ogg                                       
del LARR_53.ogg                                       
del LARR_54.ogg                                       
del LARR_55.ogg                                       
del LARR_56.ogg                                       
del scry.ogg
del stagnes.ogg
del intro1.ogg
del intro2.ogg
del intro3.ogg
del intro4.ogg
del intro5.ogg
del ThemeNEJ.ogg
del tilorn01.ogg
del tilorn02.ogg
del tilorn03.ogg
del tilorn04.ogg
del tilorn05.ogg
del tilorn06.ogg
del tilorn07.ogg
del tilorn08.ogg
del tilorn09.ogg
del tilorn10.ogg
del tilorn11.ogg
del tilorn12.ogg
del tilorn13.ogg
del tilorn14.ogg
del tilorn15.ogg
del tilorn16.ogg
del tilorn17.ogg
del tilorn18.ogg
del tilorn19.ogg
del tilorn20.ogg
del tilorn21.ogg
del tilorn22.ogg
del tilorn23.ogg
del tilorn24.ogg
del tilorn25.ogg
del tilorn26.ogg
del tilorn27.ogg
del tilorn28.ogg
del tilorn29.ogg
del tilorn30.ogg
del tilorn31.ogg
del tilorn32.ogg
del tilorn33.ogg
del CBooAct1.ogg
del CBooAct2.ogg
del CBooAct3.ogg
del CBooAtt1.ogg
del CBooAtt2.ogg
del CBooAtt3.ogg
del CBooCrHi.ogg
del CBooCrMi.ogg
del CBooHurt.ogg
del CBooSel1.ogg
del CBooSel2.ogg
del CBooSel3.ogg
del CBooSpFa.ogg
del oggdec.exe
cd..
notepad NeJ-Readme.txt