IF
	NumTimesTalkedTo(0)
	See([PC])
	!Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Dialogue([PC])
END

IF
	Global("TT8007_VISITED","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("SETH_ESCAPE","GLOBAL",1)
		DestroySelf()
END

IF
	Global("MAP_GROUP_HOSTILE10","MYAREA",0)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobal("MAP_GROUP_HOSTILE10","MYAREA",1)
		SetGlobal("SETH_ESCAPE","GLOBAL",1)
		EscapeArea()
END

IF
	!Allegiance(Myself,ENEMY)
	Global("MAP_GROUP_HOSTILE10","MYAREA",1)
	Global("SETH_ESCAPE","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("SETH_ESCAPE","GLOBAL",1)
		EscapeArea()
END

IF
	AttackedBy(NearestEnemyOf(Myself),DEFAULT)
THEN
	RESPONSE #100
		SetGlobal("SETH_ESCAPE","GLOBAL",1)
		EscapeArea()
END

IF
	!Allegiance(Myself,ENEMY)
	AttackedBy([GOODCUTOFF],DEFAULT)
THEN
	RESPONSE #100
		SetGlobal("MAP_GROUP_HOSTILE10","MYAREA",1)
		EscapeArea()
END

IF
	!StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
	See(NearestEnemyOf(Myself))
	HaveSpell(PSIONIC_DOMINATION)
THEN
	RESPONSE #100
		Spell(NearestEnemyOf(Myself),PSIONIC_DOMINATION)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(PSIONIC_DETONATE)
THEN
	RESPONSE #100
		Spell(NearestEnemyOf(Myself),PSIONIC_DETONATE)
END

IF
	!StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
	See(NearestEnemyOf(Myself))
	HaveSpell(PSIONIC_EGOWHIP)
THEN
	RESPONSE #100
		Spell(NearestEnemyOf(Myself),PSIONIC_EGOWHIP)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(PSIONIC_BALLISTIC)
THEN
	RESPONSE #100
		Spell(NearestEnemyOf(Myself),PSIONIC_BALLISTIC)
END

IF
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackReevaluate(LastSeenBy(Myself),75)
END

IF
	AttackedBy(NearestEnemyOf(Myself),DEFAULT)
THEN
	RESPONSE #100
		MoveToObject(LastAttackerOf(Myself))
END