IF
	True()
THEN
	RESPONSE #100
		CutSceneId(Player1)
		SmallWait(5)
		DisplayStringHead("Lavallin",~Sorry I ought to leave and ward the door. I'll return as soon as I am able. Farewell for now, <CHARNAME>.~)
		Wait(2)
		ActionOverride("Lavallin",ReallyForceSpell(Myself,DRYAD_TELEPORT))
		Wait(2)
		FadeToColor([30.0],0)
		Wait(3)
		FadeFromColor([30.0],0)
		MultiPlayerSync()
		Wait(2)
		EndCutSceneMode()
END


