IF
	!Global("MARKETH_GONE","GLOBAL",0)
	!Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Enemy()
		SetGlobal("MAP_GROUP_HOSTILE5","MYAREA",1)
		Continue()
END

IF
	Global("MAP_GROUP_HOSTILE5","MYAREA",0)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		SetGlobal("MAP_GROUP_HOSTILE5","MYAREA",1)
		Continue()
END

IF
	!Allegiance(Myself,ENEMY)
	!Global("MAP_GROUP_HOSTILE5","MYAREA",0)
THEN
	RESPONSE #100
		Enemy()
		Continue()
END

IF
	AttackedBy([GOODCUTOFF],DEFAULT)
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
		Enemy()
		SetGlobal("MAP_GROUP_HOSTILE5","MYAREA",1)
		Continue()
END

IF
	!StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
	See(NearestEnemyOf(Myself))
	HaveSpell(PSIONIC_DOMINATION)
THEN
	RESPONSE #100
		Spell(NearestEnemyOf(Myself),PSIONIC_DOMINATION)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(PSIONIC_DETONATE)
THEN
	RESPONSE #100
		Spell(NearestEnemyOf(Myself),PSIONIC_DETONATE)
END

IF
	!StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
	See(NearestEnemyOf(Myself))
	HaveSpell(PSIONIC_EGOWHIP)
THEN
	RESPONSE #100
		Spell(NearestEnemyOf(Myself),PSIONIC_EGOWHIP)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(PSIONIC_BALLISTIC)
THEN
	RESPONSE #100
		Spell(NearestEnemyOf(Myself),PSIONIC_BALLISTIC)
END

IF
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackReevaluate(LastSeenBy(Myself),75)
END

IF
	AttackedBy(NearestEnemyOf(Myself),DEFAULT)
THEN
	RESPONSE #100
		MoveToObject(LastAttackerOf(Myself))
END
